### PR TITLE
Added scriptcs support

### PR DESCRIPTION
**Pull request by jchannon**

### CODE REVIEW

**Comment by adamralph** [comment]
:+1: 

Should this include a change to README.md to add scriptcs to the list?

**Comment by jchannon** [comment]
Updated README :stuck_out_tongue_winking_eye:

**Comment by adamralph** [comment]
:okhand;

**Comment by jchannon** [comment]
Realised this is a fork so closing and recreated here https://github.com/rgbkrk/atom-script/pull/443

**Pull request closed without merging**
